#Trigger
on:
  push:

#Defaults of workflow for each run, will use bash shell
defaults:
  run:
    shell: bash

#Naming job
jobs:
  tf_workflow: #job id
    runs-on: ubuntu-latest
    name: "tf Workflow" #job name

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run shell commands
        run: |
          ls -l
          echo $PATH
          env | sort
          aws --version

      - name: Init
        run: |
          terraform init

      - name: Plan
        run: |
            terraform plan -out tfplan

      - name: Apply
        if: ${{ github.ref_name == 'main' }}
        run: |
            echo $GITHUB_REF_NAME
            terraform apply tfplan







